
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://172.187.193.117:5432/booking}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:170261287758-4a5n7rrpobve72ab7jkpv8673ghtgved.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}


stripe:
  secretKey: ${STRIPE_SECRET_KEY:sk_test_51RfVuEQvBB2itwygiOuVK2MND4hJ3Dksq9DAs4mEExkPHx3kQTuZYlkP845TTqrHCy5lVik4lnf8kiOs63RbWLJ500g0DK2GK0}


server:
  port: 8080

fe-server:
  port: 5173
  url: ${FE_SERVER:https://soundwave.tiktuzki.com/}

springdoc:
  api-docs:
    path: /api-docs


swagger:
  server-url: "${SERVER-URL:https://phuong.tiktuzki.com/}"

## App Properties
app:
  jwtSecret: ${JWT_SECRET:9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f}



