
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:170261287758-4a5n7rrpobve72ab7jkpv8673ghtgved.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}


kafka:
  bootstrap-servers: localhost:9092
  client-id: booking-service
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

stripe:
  secretKey: ${STRIPE_SECRET_KEY:sk_test_51RfVuEQvBB2itwygiOuVK2MND4hJ3Dksq9DAs4mEExkPHx3kQTuZYlkP845TTqrHCy5lVik4lnf8kiOs63RbWLJ500g0DK2GK0}


server:
  port: 8080

fe-server:
  port: 5173
  url: http://localhost:5173/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    config-url: /api-docs/swagger-config

swagger:
  server-url: "${SERVER-URL:http://localhost:8080/}"


